import { CommonLayout } from '@repo/ui/components/ui/commomLayout';
import AutoGeneratedMentoringForm from '../../../../../components/pages/main/mentor/auto-generated/AutoGeneratedMetoringForm';

export default function page() {
  return (
    <CommonLayout>
      <AutoGeneratedMentoringForm />
    </CommonLayout>
  );
}
