'use client';

import { useState } from 'react';
import AutoMentoringField from './AutoMentoringFeild';
import WeeklyTimeSlotSelector from './WeeklyTimeSlot';

export interface TimeSlot {
  start: string;
  end: string;
}

export interface FormValues {
  mentoringUUID: string;
  minParticipants: number;
  maxParticipants: number;
  price: number;
  deadline: string;
  timeSlots: Record<string, TimeSlot[]>;
}

export default function AutoGeneratedMentoringForm() {
  const [formValues, setFormValues] = useState<FormValues>({
    mentoringUUID: '',
    minParticipants: 1,
    maxParticipants: 1,
    price: 100,
    deadline: '2024-12-31',
    timeSlots: {},
  });
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;

    if (
      name === 'minParticipants' ||
      name === 'maxParticipants' ||
      name === 'price'
    ) {
      setFormValues((prev) => ({
        ...prev,
        [name]: parseInt(value, 10),
      }));
    } else {
      setFormValues((prev) => ({
        ...prev,
        [name]: value,
      }));
    }
  };
  const handleTimeSlotChange = (
    updatedTimeSlots: Record<string, TimeSlot[]>
  ) => {
    setFormValues((prev) => ({
      ...prev,
      timeSlots: updatedTimeSlots,
    }));
  };

  return (
    <form>
      <AutoMentoringField
        formValues={formValues}
        setFormValues={handleChange}
      />
      <WeeklyTimeSlotSelector
        formValues={formValues}
        handleTimeSlotChange={handleTimeSlotChange}
      />
    </form>
  );
}
