import AutoMentoringField from './AutoMentoringFeild';
import WeeklyTimeSlotSelector from './WeeklyTimeSlot';

export default function AutoGeneratedMetoringForm() {
  return (
    <form>
      <AutoMentoringField />
      <WeeklyTimeSlotSelector />
    </form>
  );
}
